version: "3.7"

services:
  mongodb:
    image: mongo:5.0.25-focal
    container_name: database
    env_file:
      - .env
    ports:
      - 27017:27017
  redis:
    image: redis:7.2.4-alpine
    container_name: caching
    ports:
      - 6379:6379
