import type { Buildings, ReadonlyStringArray } from "@/utils/types"

export const typesOfBuilding: Record<Buildings, ReadonlyStringArray> = {
	bar: [
		"cocktail",
		"pub",
		"wine",
		"beer",
		"sports",
		"tiki",
		"dive",
		"piano",
		"brewpub",
		"karaoke",
		"speakeasy",
		"cigar",
		"gastropub",
		"theme",
		"hotel",
		"juice",
		"rooftop",
		"gay",
		"microbrewery",
		"virtual",
	] as const,
	museum: [
		"art",
		"history",
		"science",
		"natural",
		"aviation",
		"maritime",
		"modern_art",
		"contemporary_art",
		"technology",
		"space",
		"archaeology",
		"anthropology",
		"cultural",
		"transportation",
		"botanical",
		"aquarium",
		"zoo",
		"virtual",
	] as const,
	park: [
		"national",
		"city",
		"urban",
		"wildlife",
		"botanical",
		"recreational",
		"amusement",
		"skate",
		"water",
		"adventure",
		"theme",
		"state",
		"county",
		"historic",
		"neighborhood",
		"community",
		"linear",
		"sports",
		"dog",
		"play",
	] as const,
	restaurant: [
		"italian",
		"french",
		"sushi",
		"steakhouse",
		"vegan",
		"fast_food",
		"barbecue",
		"cafe",
		"food_truck",
		"pub",
		"bistro",
		"buffet",
		"tapas",
		"brasserie",
		"diner",
		"pizzeria",
		"ramen",
		"foodcourt",
		"noodle",
		"fusion",
	] as const,
}

export const artisticMovements: ReadonlyStringArray = [
	"renaissance",
	"baroque",
	"romanticism",
	"impressionism",
	"expressionism",
	"cubism",
	"surrealism",
	"abstract expressionism",
	"pop",
	"minimalism",
	"contemporary",
	"abstract",
	"realism",
	"post-impressionism",
	"fauvism",
	"dadaism",
	"symbolism",
	"neoclassicism",
	"surrealist",
	"cubist",
]

export const listOfBuildings: ReadonlyStringArray = [
	"bar",
	"museum",
	"restaurant",
	"park",
]

export const freeOrPay: ReadonlyStringArray = ["free", "pay"]
