name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        id: node
        with:
          node-version: 20
          cache: "npm"

      - name: Run install
        run: npm ci

      - name: Run ci script
        run: npm run check
